// Auto-generated by AppKit - DO NOT EDIT
// Generated by 'npx @databricks/appkit generate-types' or Vite plugin during build
import "@databricks/appkit-ui/react";
import type { SQLTypeMarker, SQLStringMarker, SQLNumberMarker, SQLBooleanMarker, SQLBinaryMarker, SQLDateMarker, SQLTimestampMarker } from "@databricks/appkit-ui/js";

declare module "@databricks/appkit-ui/react" {
  interface QueryRegistry {
    acompanhamento: {
        name: "acompanhamento";
        parameters: Record<string, never>;
        result: Array<{
          /** Nome do vendedor responsavel pela carteira ativa do cliente. */
          vendedor: string;
          /** @sqlType BIGINT */
          na_fila: number;
          /** @sqlType BIGINT */
          trabalhados: number;
          /** @sqlType BIGINT */
          vendeu: number;
          /** @sqlType BIGINT */
          vai_pensar: number;
          /** @sqlType BIGINT */
          sem_interesse: number;
          /** @sqlType BIGINT */
          nao_atendeu: number;
        }>;
      };
    fila: {
        name: "fila";
        parameters: {
          /** STRING - use sql.string() */
          vendedor: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType INT */
          ordem_geral: number;
          /** Nome do vendedor responsavel pela carteira ativa do cliente. */
          vendedor: string;
          /** Posicao de prioridade do cliente na fila individual do vendedor (1 = maior score daquele vendedor). */
          ordem_vendedor: number;
          /** Identificador unico do cliente no CRM. */
          cliente_id: number;
          /** Razao social da empresa compradora. */
          razao_social: string;
          /** @sqlType STRING */
          cidade_uf: string;
          /** Probabilidade estimada de compra calculada pelo modelo de Machine Learning. */
          score: number;
          /** Classificacao comercial da propensao (Fria, Morna, Quente, Muito quente). */
          faixa: string;
          /** Ticket medio historico do cliente. */
          ticket_medio: number;
          /** Justificativa comercial em portugues para a realizacao do contato. */
          motivo: string;
          /** Produto recomendado para oferta com saldo atualizado no estoque. */
          sugestao: string;
          /** Desfecho da ligacao: vendeu, vai_pensar, sem_interesse ou nao_atendeu. Valores fora desse conjunto sao rejeitados por CHECK. */
          retorno_status: string;
          /** Texto livre do vendedor sobre a ligacao (ate 500 caracteres no app). Pode ser vazio. */
          retorno_comentario: string;
        }>;
      };
    kpis_semana: {
        name: "kpis_semana";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType BIGINT */
          contatos: number;
          /** @sqlType BIGINT */
          vendedores: number;
          /** @sqlType DOUBLE */
          receita_esperada: number;
          /** @sqlType STRING */
          referencia_fila: string;
          /** @sqlType DOUBLE */
          lift_top200: number;
          /** @sqlType BIGINT */
          acertos_top200: number;
          /** @sqlType DOUBLE */
          taxa_base: number;
          /** @sqlType BIGINT */
          retornos_registrados: number;
          /** @sqlType BIGINT */
          retornos_vendeu: number;
        }>;
      };
    vendedores: {
        name: "vendedores";
        parameters: Record<string, never>;
        result: Array<{
          /** Nome do vendedor responsavel pela carteira ativa do cliente. */
          vendedor: string;
        }>;
      };
  }
}
